### ISSUE TITLE
Error: Cannot find module 'jquery.sparkartTags'

### ISSUE THREAD

**Issue by Ishi-k2** [Fauntleroy/relay.js#142]
>> Error: Cannot find module 'jquery.sparkartTags' from '/root/relay/assets/scripts/views'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
root@alpha:~/relay#

my nodejs is: v0.12.0

**Comment by Fauntleroy** [comment]
Can you give me some more details on this? What operating system are you using? Which command are you running when you see this?

**Comment by Ishi-k2** [comment]
root@alpha:~# cd relay
root@alpha:~/relay# grunt -v
Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Reading package.json...OK
Parsing package.json...OK
Initializing config...OK

Registering "grunt-contrib-concat" local Npm module tasks.
Reading /root/relay/node_modules/grunt-contrib-concat/package.json...OK
Parsing /root/relay/node_modules/grunt-contrib-concat/package.json...OK
Loading "concat.js" tasks...OK
+ concat

Registering "grunt-contrib-cssmin" local Npm module tasks.
Reading /root/relay/node_modules/grunt-contrib-cssmin/package.json...OK
Parsing /root/relay/node_modules/grunt-contrib-cssmin/package.json...OK
Loading "cssmin.js" tasks...OK
+ cssmin

Registering "grunt-contrib-handlebars" local Npm module tasks.
Reading /root/relay/node_modules/grunt-contrib-handlebars/package.json...OK
Parsing /root/relay/node_modules/grunt-contrib-handlebars/package.json...OK
Loading "handlebars.js" tasks...OK
+ handlebars

Registering "grunt-contrib-stylus" local Npm module tasks.
Reading /root/relay/node_modules/grunt-contrib-stylus/package.json...OK
Parsing /root/relay/node_modules/grunt-contrib-stylus/package.json...OK
Loading "stylus.js" tasks...OK
+ stylus

Registering "grunt-contrib-uglify" local Npm module tasks.
Reading /root/relay/node_modules/grunt-contrib-uglify/package.json...OK
Parsing /root/relay/node_modules/grunt-contrib-uglify/package.json...OK
Loading "uglify.js" tasks...OK
+ uglify

Registering "grunt-contrib-watch" local Npm module tasks.
Reading /root/relay/node_modules/grunt-contrib-watch/package.json...OK
Parsing /root/relay/node_modules/grunt-contrib-watch/package.json...OK
Loading "watch.js" tasks...OK
+ watch

Registering "grunt-contrib-clean" local Npm module tasks.
Reading /root/relay/node_modules/grunt-contrib-clean/package.json...OK
Parsing /root/relay/node_modules/grunt-contrib-clean/package.json...OK
Loading "clean.js" tasks...OK
+ clean

Registering "grunt-cssjoin" local Npm module tasks.
Reading /root/relay/node_modules/grunt-cssjoin/package.json...OK
Parsing /root/relay/node_modules/grunt-cssjoin/package.json...OK
Loading "cssjoin.js" tasks...OK
+ cssjoin

Registering "grunt-browserify" local Npm module tasks.
Reading /root/relay/node_modules/grunt-browserify/package.json...OK
Parsing /root/relay/node_modules/grunt-browserify/package.json...OK
Loading "browserify.js" tasks...OK
+ browserify

Registering "grunt-contrib-jshint" local Npm module tasks.
Reading /root/relay/node_modules/grunt-contrib-jshint/package.json...OK
Parsing /root/relay/node_modules/grunt-contrib-jshint/package.json...OK
Loading "jshint.js" tasks...OK
+ jshint
Loading "Gruntfile.js" tasks...OK
+ build, buildcss, buildjs, default, dev, minify, predeploy, server

No tasks specified, running default tasks.
Running tasks: default

Running "default" task

Running "build" task

Running "buildcss" task

Running "stylus" task

Running "stylus:compile" (stylus) task
Verifying property stylus.compile exists in config...OK
Files: assets/styles/relay.styl -> assets/compiled/styles.css
Options: banner="", compress
Reading assets/styles/relay.styl...OK
Writing assets/compiled/styles.css...OK
File assets/compiled/styles.css created.
>> 1 file created.

Running "cssjoin" task

Running "cssjoin:compile" (cssjoin) task
Verifying property cssjoin.compile exists in config...OK
Files: assets/compiled/styles.css -> assets/compiled/styles.css
Options: nameArgs="cssjoin:compile", name="cssjoin", args=[], flags={}, async=undefined, errorCount=0, requires=undefined, requiresConfig=undefined, options=undefined, target="compile", data={"options":{"paths":["assets/styles"]},"files":{"assets/compiled/styles.css":["assets/compiled/styles.css"]}}, files=[{"src":["assets/compiled/styles.css"],"dest":"assets/compiled/styles.css","orig":{"src":["assets/compiled/styles.css"],"dest":"assets/compiled/styles.css"}}], filesSrc=["assets/compiled/styles.css"], paths=["assets/styles"]
Options: nameArgs="cssjoin:compile", name="cssjoin", args=[], flags={}, async=undefined, errorCount=0, requires=undefined, requiresConfig=undefined, options=undefined, target="compile", data={"options":{"paths":["assets/styles"]},"files":{"assets/compiled/styles.css":["assets/compiled/styles.css"]}}, files=[{"src":["assets/compiled/styles.css"],"dest":"assets/compiled/styles.css","orig":{"src":["assets/compiled/styles.css"],"dest":"assets/compiled/styles.css"}}], filesSrc=["assets/compiled/styles.css"], paths=["assets/styles"]
Writing assets/compiled/styles.css...OK
File assets/compiled/styles.css created.

Running "clean:css" (clean) task
Verifying property clean.css exists in config...OK
Files: [no src]
Options: force=false, no-write=false
>> 0 paths cleaned.

Running "buildjs" task

Running "jshint" task

Running "jshint:client" (jshint) task
Verifying property jshint.client exists in config...OK
Files: assets/scripts/collections/channels.js, assets/scripts/collections/connections.js, assets/scripts/collections/messages.js, assets/scripts/collections/users.js, assets/scripts/handlebars_helpers.js, assets/scripts/models/channel.js, assets/scripts/models/connection.js, assets/scripts/models/message.js, assets/scripts/models/title.js, assets/scripts/models/user.js, assets/scripts/relay.js, assets/scripts/views/channel.js, assets/scripts/views/channel_listing.js, assets/scripts/views/channels.js, assets/scripts/views/connect.js, assets/scripts/views/connection.js, assets/scripts/views/connections.js, assets/scripts/views/connectivity.js, assets/scripts/views/messages.js, assets/scripts/views/title.js, assets/scripts/views/users.js -> src
Options: force=false, reporter=null, multistr
OK
>> 21 files lint free.

Running "jshint:server" (jshint) task
Verifying property jshint.server exists in config...OK
Files: relay.js, lib/irc_adapter.js, lib/server.js -> src
Options: force=false, reporter=null, node, esnext
OK
>> 3 files lint free.

Running "handlebars" task

Running "handlebars:templates" (handlebars) task
Verifying property handlebars.templates exists in config...OK
Files: assets/templates/channel.hbs, assets/templates/channel_listing.hbs, assets/templates/channels.hbs, assets/templates/connect.hbs, assets/templates/connection.hbs, assets/templates/connections.hbs, assets/templates/connectivity.hbs, assets/templates/inline/gist.hbs, assets/templates/inline/image.hbs, assets/templates/inline/vimeo.hbs, assets/templates/inline/vine.hbs, assets/templates/inline/youtube.hbs, assets/templates/message.hbs, assets/templates/messages.hbs, assets/templates/user.hbs, assets/templates/users.hbs -> assets/compiled/templates.js
Options: namespace=false, separator="\n\n", wrapped, amd=false, commonjs, knownHelpers=[], knownHelpersOnly=false, processName=undefined
Reading assets/templates/channel.hbs...OK
Reading assets/templates/channel_listing.hbs...OK
Reading assets/templates/channels.hbs...OK
Reading assets/templates/connect.hbs...OK
Reading assets/templates/connection.hbs...OK
Reading assets/templates/connections.hbs...OK
Reading assets/templates/connectivity.hbs...OK
Reading assets/templates/inline/gist.hbs...OK
Reading assets/templates/inline/image.hbs...OK
Reading assets/templates/inline/vimeo.hbs...OK
Reading assets/templates/inline/vine.hbs...OK
Reading assets/templates/inline/youtube.hbs...OK
Reading assets/templates/message.hbs...OK
Reading assets/templates/messages.hbs...OK
Reading assets/templates/user.hbs...OK
Reading assets/templates/users.hbs...OK
Writing assets/compiled/templates.js...OK
File assets/compiled/templates.js created.
>> 1 file created.

Running "browserify" task

Running "browserify:relay" (browserify) task
Verifying property browserify.relay exists in config...OK
Files: assets/scripts/relay.js -> assets/compiled/scripts.js
Options: banner="", shim={"jquery":{"path":"assets/scripts/vendor/jquery.js","exports":"$"},"jquery-ui":{"path":"assets/scripts/vendor/jquery-ui.custom.js","exports":null,"depends":{"jquery":"$"}},"jquery.emojify":{"path":"assets/scripts/vendor/jquery.emojify.js","exports":null,"depends":{"jquery":"$"}},"jquery.links":{"path":"assets/scripts/vendor/jquery.links.js","exports":null,"depends":{"jquery":"$"}},"jquery.resize":{"path":"assets/scripts/vendor/jquery.resize.js","exports":null,"depends":{"jquery":"$"}},"jquery.serializeObject":{"path":"assets/scripts/vendor/jquery.serializeObject.js","exports":null,"depends":{"jquery":"$"}},"jquery.sparkartTags":{"path":"assets/scripts/vendor/jquery.sparkartTags.js","exports":null,"depends":{"jquery":"$"}},"bootstrap":{"path":"assets/scripts/vendor/bootstrap.js","exports":null,"depends":{"jquery":"$"}},"visibility":{"path":"assets/scripts/vendor/visibility.js","exports":"Visibility"}}
>> Error: Cannot find module 'jquery.sparkartTags' from '/root/relay/assets/scripts/views'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
root@alpha:~/relay#




--------------------------------------------------------------------------------
Os: Debian Wheezy minimalist

**Comment by Fauntleroy** [comment]
Does the file exist at `assets/scripts/vendor/jquery.sparkartTags.js`? Maybe this has to do with the way the shim paths are configured...

**Comment by Ishi-k2** [comment]
![sparkattags](https://cloud.githubusercontent.com/assets/9837539/8898971/77107cd4-33da-11e5-9f4d-3c05c69a512a.png)

:/

Maybe it will work after i reinstall Debian.

**Comment by Fauntleroy** [comment]
Thanks for looking into that for me! I'll look into possible grunt configuration problems.

**Comment by Ishi-k2** [comment]
All works normally after i reinstall Debian wheezy :)
caused by Grunt broken install.

I'm happy all just works now.
